# Generated by Django 6.1.1 on 2026-09-18 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinic", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password_hash", models.CharField(max_length=255)),
                ("full_name", models.CharField(max_length=150)),
                (
                    "role",
                    models.CharField(
                        choices=[("receptionist", "Receptionist"), ("doctor", "Doctor")],
                        default="receptionist",
                        max_length=20,
                    ),
                ),
                ("specialty", models.CharField(blank=True, default="", max_length=100)),
                ("license_number", models.CharField(blank=True, default="", max_length=50)),
                ("contact", models.CharField(blank=True, default="", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "clinic_staff_users",
                "ordering": ["full_name", "id"],
            },
        ),
        migrations.AlterModelOptions(
            name="appointment",
            options={"ordering": ["app_date", "app_time", "id"]},
        ),
        migrations.AddField(
            model_name="appointment",
            name="app_time",
            field=models.TimeField(default="09:00:00"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="reason_for_visit",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Scheduled", "Scheduled"),
                    ("Checked In", "Checked In"),
                    ("In Consultation", "In Consultation"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Scheduled",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("diagnosis", models.CharField(max_length=255)),
                ("symptoms", models.TextField(blank=True, default="")),
                ("clinical_notes", models.TextField(blank=True, default="")),
                ("prescription", models.TextField(blank=True, default="")),
                ("follow_up_advice", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="medical_records",
                        to="clinic.appointment",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_records",
                        to="clinic.patient",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_records",
                        to="clinic.staffuser",
                    ),
                ),
            ],
            options={
                "db_table": "clinic_medical_records",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="doctor_appointments",
                to="clinic.staffuser",
            ),
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                ("token", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_active", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="clinic.staffuser",
                    ),
                ),
            ],
            options={
                "db_table": "clinic_user_sessions",
                "ordering": ["-last_active"],
            },
        ),
    ]
