# Generated by Django 6.1.1 on 2026-09-18 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinic", "0002_staffuser_alter_appointment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="medicalrecord",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="doctor_records",
                to="clinic.staffuser",
            ),
        ),
        migrations.AlterField(
            model_name="medicalrecord",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="medical_records",
                to="clinic.patient",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["doctor", "app_date", "status"], name="clinic_appo_doctor__8ecc95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["app_date", "app_time"], name="clinic_appo_app_dat_0dbb5d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="medicalrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("appointment__isnull", False)),
                fields=("appointment",),
                name="unique_appointment_medical_record",
            ),
        ),
    ]
